version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: kurtay/php:sym-tut
    volumes:
      - ./app:/app
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: kurtay/nginx:sym-tut
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
